# Change these first
owner: tubul # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Protagonist
    url: https://protagonist.co.uk
  - name: Webmail
    url: https://webmail.protagonist.co.uk
  - name: Tubul
    url: https://tubul.org

status-website:
  cname: status.protagonist.co.uk
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitoring the status of Protagonist"
  introMessage: A quick overview of the status of Protagonist
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Protagonist
